import type { Metadata } from "next";
import "./globals.css";
import { SideBar } from "../ui/SideBar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="bg-gray-1100 flex h-screen">
        <SideBar />
        <div className="lg:pl-72 flex-1">
          <div className="flex-1">
              <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
